name: ashish jaiswal third script
on:
  push: 
    branches: [ main ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the content on screen
        run: echo "Welcome to GITHUB Actions"
