name: schedule cron jobs on Server
on: 
  schedule:
    - cron: "* * * * *"
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: schedule job
        run: echo "schedule job"
      
  
